### ISSUE TITLE
UserStory 10 - Calendar Tracking

### ISSUE THREAD

**Issue by Pia0912** [Pia0912/capstone-project-pia#25]
---
about: Add a calendar that displays a tracking of the hobby activities

---

# User story
As a user, I want to be able to have an calendar with a colored overview of my hobbies and when I added something to those activities, so I am able to see on what days I spend time with what hobby.

# Acceptance criteria
- [x] implement "JavaFX CalendarView"
- [ ] or find other apis/libraries
- [x] include the activity tracking
- [x] Color in the days

# Complexity
40

![Image](https://user-images.githubusercontent.com/134581160/255201074-c4b1a1e5-2a5c-4e79-a7dd-6d48e155aab3.jpg)
![Image](https://user-images.githubusercontent.com/134581160/255206006-bda91d76-5d2a-41f4-8d7e-94f497841cc1.jpg)
